---
- name: restart CUPS
  service:
          name: cups
          state: restarted
  become: yes
  listen: "restart cups"

- name: restart avahi-daemon
  service:
          name: avahi-daemon
          state: restarted
  become: yes
  listen: "restart avahi-daemon"

...
