---

- name: restart chrond
  shell: /etc/init.d/cron restart
  become: yes

- name: restart systemd-timesyncd.service
  systemd:
    name: systemd-timesyncd.service
    state: restarted

- name: reboot remote
  reboot:
    post_reboot_delay: 30
    pre_reboot_delay: 30
...
