---
- name: restart cron 
  systemd:
    name: cron
    daemon_reload: yes
    state: restart

- name: restart sshd 
  systemd:
    name: sshd
    daemon_reload: yes
    state: restarted

- name: reboot remote
  reboot:
    post_reboot_delay: 30
    pre_reboot_delay: 30
...
