---
- name: Deploy sshd banner.
  copy:
    src: issue.net
    dest: /etc/issue.net
    backup: yes
    force: yes
    mode: 0644
    owner: root
    group: root
  become: yes
  tags:
    - setup
    - ssh

- name: Deploy sshd_config.
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes
    force: yes
    mode: 0640
    owner: root
    group: root
  become: yes
  tags:
    - setup
    - ssh
  notify:
    - restart sshd
...
