---
- name: Update Apt cache
  apt:
    update-cache=yes
  become: yes

- name: Add Pre-requ packages.
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: Add Docker Apt signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker Repo.
  ansible.builtin.apt_repository:
    filename: /etc/apt/sources.list.d/docker.list
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release}} stable"
    state: present
    update-cache: yes
  become: yes

- name: Add Docker packages.
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes
...
