---
- name: Add Python3
  apt:
    name: python3
    state: present
  become: yes

- name: Add Pip for Python2
  apt:
    name: python-pip
    state: present
  become: yes

- name: Add Pip prereq for Python3
  apt:
    name: python3-venv
    state: present
  become: yes

- name: Add Pip for Python3
  apt:
    name: python3-pip
    state: present
  become: yes

...
