---
- name: Register current time zone.
  # shell: timedatectl -a | grep zone | awk '{print $3}'
  shell: timedatectl show | grep ^Timezone | awk 'BEGIN {FS = "="i}; {print $2}'
  register: default_timezone
  become: yes
  tags:
    - setup

- name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago
  become: yes
  when: default_timezone["stdout"] != "America/Chicago"
  notify:
    - restart systemd-timesyncd.service
  tags:
    - setup

- name: Remove en_GB.UTF-8 UTF-8 locale.
  lineinfile:
    path: /etc/locale.gen
    regexp: '^en_GB.UTF-8 UTF-8'
    line: '# en_GB.UTF-8 UTF-8'
    state: present
    backup: yes
  become: yes
  tags:
    - setup

- name: Enable  en_US.UTF-8 UTF-8 locale.
  lineinfile:
    path: /etc/locale.gen
    regexp: '^# en_US.UTF-8 UTF-8'
    line: en_US.UTF-8 UTF-8
    state: present
    backup: yes
  become: yes
  tags:
    - setup

- name: Deploy custom MOTD
  copy:
    src: motd
    dest: /etc/motd
    backup: yes
    force: yes
    mode: 0644
    owner: root
    group: root
  become: yes
  tags:
    - setup

- name: Create drop-in directory for timesyncd.conf
  file:
    path: /usr/local/lib/systemd/timesyncd.conf.d/
    mode: 0755
    owner: root
    group: root
    state: directory
  become: yes
  tags:
    - setup

- name: Deploy custom timesyncd.conf file
  copy:
    src: timesyncd.conf
    dest: /usr/local/lib/systemd/timesync.conf.d/
    backup: yes
    force: yes
    mode: 0644
    owner: root
    group: root
  become: yes
  notify:
    - restart systemd-timesyncd.service
  tags:
    - setup

- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'Network time on: no' in timedatectl_result.stdout"
  become: yes

...
