---
- name: Import Common tasks.
  import_tasks: common.yml

- name: Import basic network commands
  import_tasks: network.yml

- name: Import debian.yml, if needed.
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

...
