---
- name: install SAMBA
  apt:
          name: samba
          state: latest
          update_cache: yes
          autoremove: yes
          autoclean: yes
  become: yes

- name: Install custom smb.conf file
  template:
          src: smb.j2
          dest: /etc/samba/smb.conf
          owner: root
          group: root
          mode: 0644
          backup: yes
  become: yes

- name: Create SAMBA Spool directory
  file:
          path: /var/spool/samba
          mode: 1777
          owner: root
          group: root
  become: yes

- name: Restart SAMBA
  command: echo "Restarting SAMBA"
  notify: "restart samba"
  become: yes

...
